[theme]
primaryColor = "#ff914d"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#000000"
font = "sans serif"

[server]
headless = true

[client]
showErrorDetails = false
toolbarMode = "minimal"  # hides Streamlit hamburger & profile
